using System.Text.Json.Serialization;
using last.Core.GameData.Balance;
using last.Core.GameData.Static;
using last.Core.MatchHistory.Models;
using last.Core.State.Models;

namespace last.Core.Connection.WebSocket;

[JsonSourceGenerationOptions(
    WriteIndented = false,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase)]
[JsonSerializable(typeof(LcuEventPayload))]
[JsonSerializable(typeof(string[]))]
[JsonSerializable(typeof(IReadOnlyList<string>))]
[JsonSerializable(typeof(int))]
[JsonSerializable(typeof(int?))]
[JsonSerializable(typeof(string))]
[JsonSerializable(typeof(GameflowPhase))]
[JsonSerializable(typeof(GameflowPhase?))]
[JsonSerializable(typeof(GameflowSession))]
[JsonSerializable(typeof(GameflowGameData))]
[JsonSerializable(typeof(GameflowTeamPlayer))]
[JsonSerializable(typeof(IReadOnlyList<GameflowTeamPlayer>))]
[JsonSerializable(typeof(SummonerInfo))]
[JsonSerializable(typeof(IReadOnlyList<SummonerInfo>))]
[JsonSerializable(typeof(SummonerProfile))]
[JsonSerializable(typeof(ReadyCheck))]
[JsonSerializable(typeof(MatchmakingSearch))]
[JsonSerializable(typeof(IReadOnlyList<long>))]
[JsonSerializable(typeof(ChampSelectSession))]
[JsonSerializable(typeof(ChampSelectActionUpdateRequest))]
[JsonSerializable(typeof(BenchChampion))]
[JsonSerializable(typeof(IReadOnlyList<BenchChampion>))]
[JsonSerializable(typeof(ChampSelectTeamPlayer))]
[JsonSerializable(typeof(IReadOnlyList<ChampSelectTeamPlayer>))]
[JsonSerializable(typeof(ChampSelectAction))]
[JsonSerializable(typeof(IReadOnlyList<ChampSelectAction>))]
[JsonSerializable(typeof(IReadOnlyList<IReadOnlyList<ChampSelectAction>>))]
[JsonSerializable(typeof(ChampSelectTimer))]
[JsonSerializable(typeof(IReadOnlyList<int>))]
[JsonSerializable(typeof(ChampionSimple))]
[JsonSerializable(typeof(IReadOnlyList<ChampionSimple>))]
[JsonSerializable(typeof(GtimgHeroList))]
[JsonSerializable(typeof(GtimgHero))]
[JsonSerializable(typeof(IReadOnlyList<GtimgHero>))]
[JsonSerializable(typeof(OpggAramBalanceResponse))]
[JsonSerializable(typeof(OpggAramBalanceItem))]
[JsonSerializable(typeof(IReadOnlyList<OpggAramBalanceItem>))]
[JsonSerializable(typeof(LcuItemDto))]
[JsonSerializable(typeof(IReadOnlyList<LcuItemDto>))]
[JsonSerializable(typeof(ItemStaticInfo))]
[JsonSerializable(typeof(IReadOnlyList<ItemStaticInfo>))]
[JsonSerializable(typeof(GtimgKiwiAugment))]
[JsonSerializable(typeof(IReadOnlyList<GtimgKiwiAugment>))]
[JsonSerializable(typeof(List<GtimgKiwiAugment>))]
[JsonSerializable(typeof(SequenceEvent))]
[JsonSerializable(typeof(SgpMatchHistoryLol))]
[JsonSerializable(typeof(SgpGameSummaryLol))]
[JsonSerializable(typeof(SgpGameItem))]
[JsonSerializable(typeof(IReadOnlyList<SgpGameItem>))]
[JsonSerializable(typeof(SgpGameMetadata))]
[JsonSerializable(typeof(SgpGameJson))]
[JsonSerializable(typeof(SgpParticipant))]
[JsonSerializable(typeof(IReadOnlyList<SgpParticipant>))]
[JsonSerializable(typeof(SgpParticipantChallenges))]
[JsonSerializable(typeof(SgpGsmLedgeRegion))]
[JsonSerializable(typeof(SgpGsmGame))]
[JsonSerializable(typeof(SgpGsmTeamPlayer))]
[JsonSerializable(typeof(IReadOnlyList<SgpGsmTeamPlayer>))]
[JsonSerializable(typeof(SgpGsmChampionSelection))]
[JsonSerializable(typeof(IReadOnlyList<SgpGsmChampionSelection>))]
[JsonSerializable(typeof(LcuMatchHistory))]
[JsonSerializable(typeof(LcuGamesContainer))]
[JsonSerializable(typeof(LcuGameSummary))]
[JsonSerializable(typeof(IReadOnlyList<LcuGameSummary>))]
[JsonSerializable(typeof(LcuParticipant))]
[JsonSerializable(typeof(IReadOnlyList<LcuParticipant>))]
[JsonSerializable(typeof(LcuParticipantStats))]
[JsonSerializable(typeof(LcuParticipantIdentity))]
[JsonSerializable(typeof(IReadOnlyList<LcuParticipantIdentity>))]
[JsonSerializable(typeof(LcuPlayerIdentity))]
[JsonSerializable(typeof(EntitlementsToken))]
[JsonSerializable(typeof(UnifiedMatchSummary))]
[JsonSerializable(typeof(IReadOnlyList<UnifiedMatchSummary>))]
[JsonSerializable(typeof(UnifiedParticipant))]
[JsonSerializable(typeof(IReadOnlyList<UnifiedParticipant>))]
[JsonSerializable(typeof(UnifiedTeamMember))]
[JsonSerializable(typeof(IReadOnlyList<UnifiedTeamMember>))]
[JsonSerializable(typeof(SgpGameDetailsLol))]
[JsonSerializable(typeof(SgpGameDetailsJson))]
[JsonSerializable(typeof(SgpTimelineFrame))]
[JsonSerializable(typeof(IReadOnlyList<SgpTimelineFrame>))]
[JsonSerializable(typeof(SgpTimelineEvent))]
[JsonSerializable(typeof(IReadOnlyList<SgpTimelineEvent>))]
[JsonSerializable(typeof(LcuGameTimeline))]
[JsonSerializable(typeof(LcuTimelineFrame))]
[JsonSerializable(typeof(IReadOnlyList<LcuTimelineFrame>))]
[JsonSerializable(typeof(LcuTimelineEvent))]
[JsonSerializable(typeof(IReadOnlyList<LcuTimelineEvent>))]
[JsonSerializable(typeof(UnifiedMatchDetails))]
[JsonSerializable(typeof(UnifiedTimelineFrame))]
[JsonSerializable(typeof(IReadOnlyList<UnifiedTimelineFrame>))]
[JsonSerializable(typeof(UnifiedTimelineEvent))]
[JsonSerializable(typeof(IReadOnlyList<UnifiedTimelineEvent>))]
public sealed partial class LcuJsonSerializerContext : JsonSerializerContext;